services:
  postgresql:
    image: mysterias/postgresdb:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5433:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dain -d energy_monitor"]
      interval: 5s
      timeout: 3s
      retries: 10

  fastapi:
    image: mysterias:web-service:latest
    container_name: fastapi
    depends_on:
      postgresql:
        condition: service_healthy
    env_file: "docker.env"
    ports: ["8080:8080"]
    restart: on-failure
