kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http-gateway
  namespace: web
spec:
  gatewayClassName: gke-l7-regional-external-managed # GKE's managed external Application Load Balancer
  listeners:
    - name: http
      protocol: HTTP
      port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-route
  namespace: web
spec:
  parentRefs:
    - name: http-gateway
      kind: Gateway
      sectionName: http
  rules:
    - backendRefs:
        - port: 80
          name: server-svc
