apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: fastapi-health-policy
  namespace: web
spec:
  targetRef:
    group: ""
    kind: Service
    name: server-svc
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /
